Repository umr-lops/xsarsea, pull requests merged in 2024-11, with the labels that each got.

#81 Migrate from `setup.py` to `pyproject.toml`
  .github/release.yml
  .github/workflows/ci.yaml
  .github/workflows/conda-feedstock-check.yml
  .github/workflows/main.yml
  .github/workflows/upstream-dev.yaml
  .pre-commit-config.yaml
  ci/install-upstream-dev.sh
  ci/requirements/docs.yaml
  ci/requirements/environment.yaml
  docs/basic_api.rst
  docs/examples/create_hh_lut.ipynb
  docs/examples/gmfs_and_luts.ipynb
  docs/examples/streaks.ipynb
  docs/examples/windspeed_retrieval_L1.ipynb
  docs/examples/xsarsea.ipynb
  docs/index.rst
  docs/installing.rst
  pyproject.toml
  setup.py
  src/scripts/xsarsea_cli.py
  src/xsarsea/__init__.py
  src/xsarsea/detrend.py
  src/xsarsea/gradients.py
  src/xsarsea/utils.py
  src/xsarsea/windspeed/__init__.py
  src/xsarsea/windspeed/cmod7.py
  src/xsarsea/windspeed/gmfs.py
  src/xsarsea/windspeed/gmfs_impl.py
  src/xsarsea/windspeed/models.py
  src/xsarsea/windspeed/pickle_luts.py
  src/xsarsea/windspeed/utils.py
  src/xsarsea/windspeed/windspeed.py
  test/test_xsarsea.py
Labels: bug, enhancement

#82 missing `dynamc_matrix` for CI
  .github/actions/dynamic_matrix.py
  .github/workflows/ci.yaml
  README.rst
  ci/requirements/environment.yaml
  pyproject.toml
  src/xsarsea/utils.py
  src/xsarsea/windspeed/utils.py
Labels: bug

#80 update xsarsea
  src/xsarsea/gradients.py
  src/xsarsea/utils.py
  src/xsarsea/windspeed/models.py
  src/xsarsea/windspeed/utils.py
  src/xsarsea/windspeed/windspeed.py
Labels: enhancement
